### ISSUE TITLE
Function Example

### ISSUE THREAD

**Issue by yusufarist** [zendaokab/msaeRB#1]
Hello, can you (@zendaokab) help me use this package? Is there any documentation of its use? For example, code samples and results? Thank you 😀✨

**Comment by zendaokab** [comment]
Yes of course. First you can install 'msaeRB' package in your R. Then you
can follow the example that available in R by click help and search msaeRB

**Comment by yusufarist** [comment]
Thanks for responsing

**Comment by zendaokab** [comment]
Thank you Yusuf for trying my package 🙏
